# Generated by Django 3.0.5 on 2020-05-17 18:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgRecetas/'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recetario.usuarios'),
        ),
    ]
