# Generated by Django 3.0.5 on 2020-05-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0003_auto_20200517_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='imagen',
            new_name='imagenMuestra',
        ),
        migrations.CreateModel(
            name='pasosReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.TextField()),
                ('pasoNumer', models.SmallIntegerField()),
                ('recta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.recetas')),
            ],
        ),
        migrations.CreateModel(
            name='imgReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgRecetas/')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.recetas')),
            ],
        ),
    ]
