# Generated by Django 3.0.5 on 2020-05-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0004_auto_20200520_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasosreceta',
            old_name='recta',
            new_name='receta',
        ),
    ]
